const initialUser = {
  // idMap is ...
  idMap: "",
  // nameMap is ...
  nameMap: "",
  // emailMap is ...
  emailMap: "",
  // passwordMap is ...
  passwordMap: "",
};

export default initialUser;
